nguage: node_js

node_js:
    - 6.10.3

notifications:
  email:
    on_failure: change
    on_success: change

branches:
  only:
    - master

install:
  - npm install -g firebase-tools 
  - npm install

script:
  - npm run build


after_success:
  - firebase deploy --token  $FIREBASE_TOKEN

